/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafa3;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author jason
 */
public class Kinky extends javax.swing.JFrame {

    /**
     * Creates new form Kinky
     */
    public Kinky() {
        initComponents();
//        txtAccNr.setVisible(true);
//        txtAccNr.setText("" + id);
//        txtAccNr1.setVisible(true);
//        txtAccNr1.setText("" + current);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nyash = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        booba = new javax.swing.JButton();
        stelthy_escort = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Enter Amount:");

        booba.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        booba.setForeground(new java.awt.Color(255, 0, 0));
        booba.setText("Withdraw");
        booba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boobaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(booba)
                            .addComponent(nyash, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(173, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stelthy_escort)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(stelthy_escort)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(booba)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boobaActionPerformed
        Integer bottoms = 0;  
        Double ahegao = 0.00;
        try{
            Integer crush_me_onee_chan = Integer.parseInt(stelthy_escort.getText());
            Connection break_me_onee_chan = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","Jason1601");  
            PreparedStatement sit_on_me_onee_chan = break_me_onee_chan.prepareStatement("SELECT * FROM users WHERE ID = ?");  
            sit_on_me_onee_chan.setInt(1, crush_me_onee_chan);            
            ResultSet furry = sit_on_me_onee_chan.executeQuery();  
            if (furry.next()) {  
                bottoms = furry.getInt("ID");
                ahegao = furry.getDouble("CURRENTBALANCE");
            }
        }
        catch(NumberFormatException | SQLException nyash){
            JOptionPane.showMessageDialog(null, "Oof, sorry...");
        }
        if(ahegao > Double.parseDouble(nyash.getText())){
            try{
                Connection domme = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","Jason1601");
                Double feet = (ahegao - Integer.parseInt(nyash.getText()));
                PreparedStatement toes = domme.prepareStatement("UPDATE users SET CURRENTBALANCE = " + feet + "WHERE ID = " + bottoms);
                toes.executeUpdate();
            }           
            catch(NumberFormatException | SQLException nyash){
                JOptionPane.showMessageDialog(null, "Oof, sorry...");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Nah fam, you ain't got the dough");
        }
    }//GEN-LAST:event_boobaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kinky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kinky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kinky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kinky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kinky().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nyash;
    public javax.swing.JLabel stelthy_escort;
    // End of variables declaration//GEN-END:variables
}
